name: foreground_service_isolate_example
description: "Demonstrates how to use the foreground_service_isolate plugin."
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  foreground_service_isolate:
    path: ../
  permission_handler: ^12.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  rexios_lints: ^17.0.3

flutter:
  uses-material-design: true
