name: foreground_service_isolate
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  isolate_channel: ^0.4.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^17.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.iodesignteam.foreground_service_isolate
        pluginClass: ForegroundServiceIsolatePlugin
