name: foreground_service_isolate
description: Spawn a long-running Flutter isolate in a foreground service
version: 0.1.0
homepage: https://github.com/IO-Design-Team/foreground_service_isolate

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  isolate_channel: ^0.6.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^17.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.iodesignteam.foreground_service_isolate
        pluginClass: ForegroundServiceIsolatePlugin
